/** Colour swatches offered when creating or editing an appointment. */
export const APPOINTMENT_COLORS = [
  { name: 'Azure', value: '#1e88e5' },
  { name: 'Teal', value: '#00897b' },
  { name: 'Green', value: '#43a047' },
  { name: 'Lime', value: '#c0ca33' },
  { name: 'Amber', value: '#ffb300' },
  { name: 'Orange', value: '#fb8c00' },
  { name: 'Red', value: '#e53935' },
  { name: 'Pink', value: '#d81b60' },
  { name: 'Purple', value: '#8e24aa' },
  { name: 'Indigo', value: '#3949ab' },
  { name: 'Brown', value: '#6d4c41' },
  { name: 'Slate', value: '#546e7a' },
] as const;

/** Themes the icon picker is narrowed to, in the order they appear in its dropdown. */
export const APPOINTMENT_ICON_GROUPS = [
  'General',
  'Celebrations',
  'School & work',
  'Travel & seasons',
  'Home & errands',
  'Health & sport',
] as const;

export type AppointmentIconGroup = (typeof APPOINTMENT_ICON_GROUPS)[number];

export interface AppointmentIcon {
  name: string;
  /** Lucide icon name, as stored on the appointment. */
  value: string;
  group: AppointmentIconGroup;
}

/**
 * Icons offered when creating or editing an appointment. Their SVGs live in
 * `appointment-icon-svgs.ts` and are loaded on demand, not with the app shell.
 * Stored appointments keep the icon's value, so the order can change freely;
 * the first entry is the default.
 */
export const APPOINTMENT_ICONS: readonly AppointmentIcon[] = [
  { name: 'Calendar', value: 'lucideCalendar', group: 'General' },
  { name: 'Calendar check', value: 'lucideCalendarCheck', group: 'General' },
  { name: 'Calendar clock', value: 'lucideCalendarClock', group: 'General' },
  { name: 'Calendar heart', value: 'lucideCalendarHeart', group: 'General' },
  { name: 'Flag', value: 'lucideFlag', group: 'General' },
  { name: 'Star', value: 'lucideStar', group: 'General' },
  { name: 'Heart', value: 'lucideHeart', group: 'General' },
  { name: 'Bell', value: 'lucideBell', group: 'General' },
  { name: 'Alarm', value: 'lucideAlarmClock', group: 'General' },
  { name: 'Clock', value: 'lucideClock', group: 'General' },
  { name: 'Hourglass', value: 'lucideHourglass', group: 'General' },
  { name: 'Timer', value: 'lucideTimer', group: 'General' },
  { name: 'Checklist', value: 'lucideListChecks', group: 'General' },
  { name: 'To-do', value: 'lucideListTodo', group: 'General' },
  { name: 'Deadline', value: 'lucideFileText', group: 'General' },
  { name: 'Bookmark', value: 'lucideBookmark', group: 'General' },
  { name: 'Pin', value: 'lucidePin', group: 'General' },
  { name: 'Location', value: 'lucideMapPin', group: 'General' },
  { name: 'Target', value: 'lucideTarget', group: 'General' },
  { name: 'Rocket', value: 'lucideRocket', group: 'General' },
  { name: 'Sparkles', value: 'lucideSparkles', group: 'General' },
  { name: 'Lightning', value: 'lucideZap', group: 'General' },
  { name: 'Idea', value: 'lucideLightbulb', group: 'General' },
  { name: 'Announcement', value: 'lucideMegaphone', group: 'General' },
  { name: 'Crown', value: 'lucideCrown', group: 'General' },
  { name: 'Smile', value: 'lucideSmile', group: 'General' },
  { name: 'Thumbs up', value: 'lucideThumbsUp', group: 'General' },
  { name: 'Party', value: 'lucidePartyPopper', group: 'Celebrations' },
  { name: 'Cake', value: 'lucideCake', group: 'Celebrations' },
  { name: 'Cake slice', value: 'lucideCakeSlice', group: 'Celebrations' },
  { name: 'Gift', value: 'lucideGift', group: 'Celebrations' },
  { name: 'Baby', value: 'lucideBaby', group: 'Celebrations' },
  { name: 'Wedding', value: 'lucideGem', group: 'Celebrations' },
  { name: 'Love', value: 'lucideHeartHandshake', group: 'Celebrations' },
  { name: 'Church', value: 'lucideChurch', group: 'Celebrations' },
  { name: 'Christmas', value: 'lucideTreePine', group: 'Celebrations' },
  { name: 'Easter', value: 'lucideEgg', group: 'Celebrations' },
  { name: 'Halloween', value: 'lucideGhost', group: 'Celebrations' },
  { name: 'Candle', value: 'lucideFlame', group: 'Celebrations' },
  { name: 'Flowers', value: 'lucideFlower2', group: 'Celebrations' },
  { name: 'Event', value: 'lucideTicket', group: 'Celebrations' },
  { name: 'Music', value: 'lucideMusic', group: 'Celebrations' },
  { name: 'Guitar', value: 'lucideGuitar', group: 'Celebrations' },
  { name: 'Microphone', value: 'lucideMic', group: 'Celebrations' },
  { name: 'Theatre', value: 'lucideDrama', group: 'Celebrations' },
  { name: 'Cinema', value: 'lucideClapperboard', group: 'Celebrations' },
  { name: 'Popcorn', value: 'lucidePopcorn', group: 'Celebrations' },
  { name: 'Photo', value: 'lucideCamera', group: 'Celebrations' },
  { name: 'Wine', value: 'lucideWine', group: 'Celebrations' },
  { name: 'Beer', value: 'lucideBeer', group: 'Celebrations' },
  { name: 'Cocktail', value: 'lucideMartini', group: 'Celebrations' },
  { name: 'Sweets', value: 'lucideCandy', group: 'Celebrations' },
  { name: 'Ice cream', value: 'lucideIceCreamCone', group: 'Celebrations' },
  { name: 'Graduation', value: 'lucideGraduationCap', group: 'School & work' },
  { name: 'Exam', value: 'lucideBookOpen', group: 'School & work' },
  { name: 'Book', value: 'lucideBook', group: 'School & work' },
  { name: 'Notes', value: 'lucideNotebookPen', group: 'School & work' },
  { name: 'School', value: 'lucideSchool', group: 'School & work' },
  { name: 'Library', value: 'lucideLibrary', group: 'School & work' },
  { name: 'Backpack', value: 'lucideBackpack', group: 'School & work' },
  { name: 'Calculator', value: 'lucideCalculator', group: 'School & work' },
  { name: 'Lab', value: 'lucideFlaskConical', group: 'School & work' },
  { name: 'Microscope', value: 'lucideMicroscope', group: 'School & work' },
  { name: 'Work', value: 'lucideBriefcase', group: 'School & work' },
  { name: 'Meeting', value: 'lucideUsers', group: 'School & work' },
  { name: 'Presentation', value: 'lucidePresentation', group: 'School & work' },
  { name: 'Laptop', value: 'lucideLaptop', group: 'School & work' },
  { name: 'Office', value: 'lucideBuilding2', group: 'School & work' },
  { name: 'Mail', value: 'lucideMail', group: 'School & work' },
  { name: 'Call', value: 'lucidePhone', group: 'School & work' },
  { name: 'Video call', value: 'lucideVideo', group: 'School & work' },
  { name: 'Chat', value: 'lucideMessageSquare', group: 'School & work' },
  { name: 'Clipboard', value: 'lucideClipboardList', group: 'School & work' },
  { name: 'Folder', value: 'lucideFolderOpen', group: 'School & work' },
  { name: 'Chart', value: 'lucideChartColumn', group: 'School & work' },
  { name: 'Award', value: 'lucideAward', group: 'School & work' },
  { name: 'Certificate', value: 'lucideBadgeCheck', group: 'School & work' },
  { name: 'Deal', value: 'lucideHandshake', group: 'School & work' },
  { name: 'Code', value: 'lucideCode', group: 'School & work' },
  { name: 'Flight', value: 'lucidePlane', group: 'Travel & seasons' },
  { name: 'Take-off', value: 'lucidePlaneTakeoff', group: 'Travel & seasons' },
  { name: 'Train', value: 'lucideTrainFront', group: 'Travel & seasons' },
  { name: 'Bus', value: 'lucideBus', group: 'Travel & seasons' },
  { name: 'Car', value: 'lucideCar', group: 'Travel & seasons' },
  { name: 'Bike', value: 'lucideBike', group: 'Travel & seasons' },
  { name: 'Ship', value: 'lucideShip', group: 'Travel & seasons' },
  { name: 'Sailing', value: 'lucideSailboat', group: 'Travel & seasons' },
  { name: 'Hotel', value: 'lucideHotel', group: 'Travel & seasons' },
  { name: 'Luggage', value: 'lucideLuggage', group: 'Travel & seasons' },
  { name: 'Map', value: 'lucideMap', group: 'Travel & seasons' },
  { name: 'Compass', value: 'lucideCompass', group: 'Travel & seasons' },
  { name: 'World', value: 'lucideGlobe', group: 'Travel & seasons' },
  { name: 'Sightseeing', value: 'lucideLandmark', group: 'Travel & seasons' },
  { name: 'Holiday', value: 'lucideUmbrella', group: 'Travel & seasons' },
  { name: 'Beach', value: 'lucideTreePalm', group: 'Travel & seasons' },
  { name: 'Sea', value: 'lucideWaves', group: 'Travel & seasons' },
  { name: 'Camping', value: 'lucideTent', group: 'Travel & seasons' },
  { name: 'Caravan', value: 'lucideCaravan', group: 'Travel & seasons' },
  { name: 'Mountains', value: 'lucideMountain', group: 'Travel & seasons' },
  { name: 'Skiing', value: 'lucideMountainSnow', group: 'Travel & seasons' },
  { name: 'Summer', value: 'lucideSun', group: 'Travel & seasons' },
  { name: 'Winter', value: 'lucideSnowflake', group: 'Travel & seasons' },
  { name: 'Autumn', value: 'lucideLeaf', group: 'Travel & seasons' },
  { name: 'Spring', value: 'lucideSprout', group: 'Travel & seasons' },
  { name: 'Rain', value: 'lucideCloudRain', group: 'Travel & seasons' },
  { name: 'Weather', value: 'lucideCloudSun', group: 'Travel & seasons' },
  { name: 'Fuel', value: 'lucideFuel', group: 'Travel & seasons' },
  { name: 'Home', value: 'lucideHouse', group: 'Home & errands' },
  { name: 'Moving', value: 'lucideTruck', group: 'Home & errands' },
  { name: 'Keys', value: 'lucideKey', group: 'Home & errands' },
  { name: 'Sofa', value: 'lucideSofa', group: 'Home & errands' },
  { name: 'Bed', value: 'lucideBed', group: 'Home & errands' },
  { name: 'Lamp', value: 'lucideLamp', group: 'Home & errands' },
  { name: 'Repair', value: 'lucideHammer', group: 'Home & errands' },
  { name: 'Tools', value: 'lucideWrench', group: 'Home & errands' },
  { name: 'Painting', value: 'lucidePaintbrush', group: 'Home & errands' },
  { name: 'Electricity', value: 'lucidePlug', group: 'Home & errands' },
  { name: 'Laundry', value: 'lucideWashingMachine', group: 'Home & errands' },
  { name: 'Clothes', value: 'lucideShirt', group: 'Home & errands' },
  { name: 'Hairdresser', value: 'lucideScissors', group: 'Home & errands' },
  { name: 'Parcel', value: 'lucidePackage', group: 'Home & errands' },
  { name: 'Food', value: 'lucideUtensils', group: 'Home & errands' },
  { name: 'Cooking', value: 'lucideChefHat', group: 'Home & errands' },
  { name: 'Coffee', value: 'lucideCoffee', group: 'Home & errands' },
  { name: 'Pizza', value: 'lucidePizza', group: 'Home & errands' },
  { name: 'Groceries', value: 'lucideApple', group: 'Home & errands' },
  { name: 'Shopping', value: 'lucideShoppingCart', group: 'Home & errands' },
  { name: 'Shopping bag', value: 'lucideShoppingBag', group: 'Home & errands' },
  { name: 'Store', value: 'lucideStore', group: 'Home & errands' },
  { name: 'Money', value: 'lucideBanknote', group: 'Home & errands' },
  { name: 'Card', value: 'lucideCreditCard', group: 'Home & errands' },
  { name: 'Savings', value: 'lucidePiggyBank', group: 'Home & errands' },
  { name: 'Bill', value: 'lucideReceipt', group: 'Home & errands' },
  { name: 'Wallet', value: 'lucideWallet', group: 'Home & errands' },
  { name: 'Internet', value: 'lucideWifi', group: 'Home & errands' },
  { name: 'Health', value: 'lucideStethoscope', group: 'Health & sport' },
  { name: 'Medicine', value: 'lucidePill', group: 'Health & sport' },
  { name: 'Vaccination', value: 'lucideSyringe', group: 'Health & sport' },
  { name: 'Hospital', value: 'lucideHospital', group: 'Health & sport' },
  { name: 'Heartbeat', value: 'lucideHeartPulse', group: 'Health & sport' },
  { name: 'Fitness', value: 'lucideActivity', group: 'Health & sport' },
  { name: 'Temperature', value: 'lucideThermometer', group: 'Health & sport' },
  { name: 'Plaster', value: 'lucideBandage', group: 'Health & sport' },
  { name: 'Mind', value: 'lucideBrain', group: 'Health & sport' },
  { name: 'Eyes', value: 'lucideEye', group: 'Health & sport' },
  { name: 'Sport', value: 'lucideDumbbell', group: 'Health & sport' },
  { name: 'Running', value: 'lucideFootprints', group: 'Health & sport' },
  { name: 'Trophy', value: 'lucideTrophy', group: 'Health & sport' },
  { name: 'Medal', value: 'lucideMedal', group: 'Health & sport' },
  { name: 'Volleyball', value: 'lucideVolleyball', group: 'Health & sport' },
  { name: 'Goal', value: 'lucideGoal', group: 'Health & sport' },
  { name: 'Swimming', value: 'lucideLifeBuoy', group: 'Health & sport' },
  { name: 'Yoga', value: 'lucidePersonStanding', group: 'Health & sport' },
  { name: 'Pet', value: 'lucidePawPrint', group: 'Health & sport' },
  { name: 'Dog', value: 'lucideDog', group: 'Health & sport' },
  { name: 'Cat', value: 'lucideCat', group: 'Health & sport' },
  { name: 'Fish', value: 'lucideFish', group: 'Health & sport' },
  { name: 'Bird', value: 'lucideBird', group: 'Health & sport' },
  { name: 'Rabbit', value: 'lucideRabbit', group: 'Health & sport' },
];

export const DEFAULT_APPOINTMENT_COLOR: string = APPOINTMENT_COLORS[0].value;
export const DEFAULT_APPOINTMENT_ICON: string = APPOINTMENT_ICONS[0]!.value;

/** The group an icon belongs to, or the first group for an icon not on offer. */
export function groupOfIcon(value: string): AppointmentIconGroup {
  return (
    APPOINTMENT_ICONS.find((icon) => icon.value === value)?.group ?? APPOINTMENT_ICON_GROUPS[0]
  );
}
